# Generated by Django 3.2.16 on 2023-01-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Food', 'Food')], default='Food', max_length=10),
        ),
    ]
